services:
  scylla:
    image: "scylladb/scylla"
    ports:
      - "9042:9042/tcp"
    command: "--smp 1 --memory=750M --overprovisioned 1"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.3
    ports:
      - 9200:9200
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=password
